---
common_packages:
  - ca-certificates
  - curl
  - jq
  - iproute2
  - ipset
  - iptables
  - ufw
  - software-properties-common
  - python3-cryptography
  - ssss
  - openssl
awg_backup_root: /root/config-backups
awg_enable_fail2ban: true
