---
- name: "Проверка: DNS ENTRY сервера - этап 1"
  ansible.builtin.stat:
    path: "{{ entry_dns_destination_path }}"
  register: entry_dns_live_file

- name: "Проверка: DNS ENTRY сервера - этап 2"
  ansible.builtin.command:
    argv:
      - /usr/bin/cmp
      - --silent
      - "{{ entry_dns_destination_path }}"
      - "{{ entry_dns_source_path }}"
  register: entry_dns_file_compare
  changed_when: false
  failed_when: entry_dns_file_compare.rc not in [0, 1]
  when: entry_dns_live_file.stat.exists

- name: "Определение: DNS ENTRY сервера - этап 3"
  ansible.builtin.set_fact:
    entry_dns_file_changed: >-
      {{ (not entry_dns_live_file.stat.exists) or
         (entry_dns_file_compare.rc | default(1) == 1) }}

- name: "Создание: DNS ENTRY сервера - этап 4"
  ansible.builtin.file:
    path: "{{ entry_dns_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  when:
    - entry_dns_live_file.stat.exists
    - entry_dns_file_changed | bool

- name: "Резервное копирование: DNS ENTRY сервера - этап 5"
  ansible.builtin.copy:
    src: "{{ entry_dns_destination_path }}"
    dest: >-
      {{ entry_dns_backup_dir }}/{{ entry_dns_file.name }}.{{ ansible_date_time.iso8601_basic_short }}
    remote_src: true
    owner: root
    group: root
    mode: "0600"
  when:
    - entry_dns_live_file.stat.exists
    - entry_dns_file_changed | bool

- name: "Установка: DNS ENTRY сервера - этап 6"
  ansible.builtin.copy:
    src: "{{ entry_dns_source_path }}"
    dest: "{{ entry_dns_destination_path }}"
    remote_src: true
    owner: root
    group: root
    mode: "0644"
  when: entry_dns_file_changed | bool
  notify: "{{ 'Перезапустить dnsmasq' if entry_dns_service_to_restart == 'dnsmasq.service' else 'Перезапустить Unbound' }}"
